name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      - name: Upload built PDF to repo
        uses: EndBug/add-and-commit@v8
        with:
          add: 'cv.pdf --force'
          committer_name: 'GitHub Actions'
          message: 'Update pdf'

